- .github/workflows/api.yaml
enhancement
___
- Added a new GitHub Actions workflow in `.github/workflows/api.yaml` that triggers on push and pull request events.
- The workflow is designed to validate the code in the `apps/api` directory using ESLint.
- The workflow runs on an Ubuntu-latest environment and uses Node.js version 20 and pnpm version 8 for package management.
- The workflow steps include checking out the code, setting up Node.js and pnpm, installing packages, and running the linting command.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> build(cli): Add lint workflow for API

- .github/workflows/api.yaml
- apps/web/app/page.tsx
- apps/web/components/Links.tsx
Enhancement
___
This PR introduces changes to make the landing page of the application mobile responsive. The main changes include:
- Adjustments to the layout and sizing of elements on the landing page to ensure they fit and display properly on smaller screens.
- Changes to the text size in the Links component to be responsive, displaying smaller on mobile and larger on desktop screens.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat: responsive landing

- apps/api/src/auth/service/auth.service.ts
- apps/api/src/mail/services/mail.service.ts
bug_fix
___
This PR addresses a bug related to the email sending operations in the application. Previously, these operations were performed synchronously, which could potentially block the execution of the application. The changes in this PR make these operations asynchronous, improving the application's performance and responsiveness. The affected operations include:
- Sending OTP for login
- Sending project invitation emails for non-registered users
- Sending general emails
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> patch: send email async

- apps/api/src/app/app.module.ts
- apps/api/src/common/cleanup.ts
- apps/api/src/common/create-event.ts
- apps/api/src/common/get-default-project-environemnt.ts
- apps/api/src/common/get-variable-with-authority.ts
- apps/api/src/event/controller/event.controller.ts
- apps/api/src/event/event.e2e.spec.ts
- apps/api/src/event/service/event.service.ts
- apps/api/src/prisma/migrations/20240219163241_add_variable/migration.sql
- apps/api/src/prisma/schema.prisma
- apps/api/src/secret/service/secret.service.ts
- apps/api/src/variable/controller/variable.controller.spec.ts
- apps/api/src/variable/controller/variable.controller.ts
- apps/api/src/variable/dto/create.variable/create.variable.spec.ts
- apps/api/src/variable/dto/create.variable/create.variable.ts
- apps/api/src/variable/dto/update.variable/update.variable.spec.ts
- apps/api/src/variable/dto/update.variable/update.variable.ts
- apps/api/src/variable/service/variable.service.spec.ts
- apps/api/src/variable/service/variable.service.ts
- apps/api/src/variable/variable.e2e.spec.ts
- apps/api/src/variable/variable.module.ts
- apps/api/src/variable/variable.types.ts
Fixes #91
___
___
- Introduced the `VariableModule` for managing variables within the application.
- Added CRUD operations for variables including version management.
- Extended event handling to support variable-related events.
- Implemented utility functions for fetching variables with authority checks and default project environments.
- Added comprehensive tests covering new variable functionality and related event handling.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>13 files</summary><table>
<tr>
<td>
<details>
<summary><strong>app.module.ts</strong><dd><code>Integrate Variable Module into App Module</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat(api): Add support for storing and managing variables

- apps/api/src/api-key/api-key.e2e.spec.ts
- apps/api/src/api-key/controller/api-key.controller.ts
- apps/api/src/api-key/service/api-key.service.ts
- apps/api/src/auth/auth.e2e.spec.ts
- apps/api/src/auth/controller/auth.controller.ts
- apps/api/src/auth/service/auth.service.ts
- apps/api/src/environment/controller/environment.controller.ts
- apps/api/src/environment/service/environment.service.ts
- apps/api/src/project/controller/project.controller.ts
- apps/api/src/project/service/project.service.ts
- apps/api/src/secret/controller/secret.controller.ts
- apps/api/src/secret/service/secret.service.ts
- apps/api/src/workspace-role/controller/workspace-role.controller.ts
- apps/api/src/workspace-role/service/workspace-role.service.ts
- apps/api/src/workspace/controller/workspace.controller.ts
- apps/api/src/workspace/service/workspace.service.ts
- apps/api/src/workspace/workspace.e2e.spec.ts
___
- Simplified API endpoints by removing admin-specific paths and guards.
- Updated e2e tests to reflect the new API endpoint paths.
- Commented out or removed methods for admin-specific data retrieval across services.
- Enhanced security and maintainability by streamlining access to resources.
___
</strong></td><td><details><summary>14 files</summary><table>
<tr>
<td>
<details>
<summary><strong>api-key.e2e.spec.ts</strong><dd><code>Update API Endpoint in Api Key E2E Tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
apps/api/src/api-key/api-key.e2e.spec.ts …
> test(api): Improve coverage

- apps/api/src/secret/dto/create.secret/create.secret.ts
- apps/api/src/variable/dto/create.variable/create.variable.ts
- apps/api/src/workspace/controller/workspace.controller.ts
- apps/api/src/workspace/service/workspace.service.ts
- apps/api/src/workspace/workspace.e2e.spec.ts
Fixes #128
___
___
- Added functionality to export data of a workspace including details, roles, projects, environments, variables, and secrets.
- Refactored `environmentId` field in `CreateSecret` and `CreateVariable` DTOs from number to string.
- Introduced a new endpoint `:workspaceId/export-data` in `WorkspaceController` with `WORKSPACE_ADMIN` authority requirement.
- Implemented `exportData` method in `WorkspaceService` to support the data export feature.
- Added comprehensive e2e tests to validate the new export data functionality, including checks for unauthorized access and successful data export.
___
<tr>
<td>
<details> …
> feat(api): Add feature to export data of a workspace

- docs/contributing-to-keyshade/environment-variables.md
Fixed typo in Docs/environment-variables.md file <br />
___
documentation
___
- Corrected a typo in the environment variables documentation, ensuring the correct abbreviation for SMTP is used.
___
<tr>
<td>
<details>
<summary><strong>environment-variables.md</strong><dd><code>Fix Typo in Environment Variables Documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/contributing-to-keyshade/environment-variables.md
<li>Corrected the typo from "SMPT" to "SMTP" in the description of the <br><code>SMTP_PORT</code> environment variable.<br>
</details>
</td>
<td><a …
> docs: fix typo in environment-variables.md

- apps/api/src/auth/controller/auth.controller.ts
- apps/api/src/common/static.ts
- apps/api/src/main.ts
- apps/api/src/user/controller/user.controller.ts
- apps/api/src/user/dto/create.user/create.user.ts
documentation, enhancement
___
- Enhanced Swagger documentation across various controllers and DTOs for better API documentation.
- Refactored OTP validation endpoint parameters from `ApiParam` to `ApiQuery`.
- Added authentication and security definitions to Swagger configuration in `main.ts`.
- Documented user controller endpoints with detailed request and response schemas.
___
<tr>
<td>
<details>
<summary><strong>auth.controller.ts</strong><dd><code>Refactor OTP Validation Endpoint Parameters</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> docs(api): Add swagger docs of User Controller

- docs/contributing-to-keyshade/design-of-our-code/api.md
- docs/contributing-to-keyshade/environment-variables.md
- docs/contributing-to-keyshade/prerequisites.md
- Removed Supabase Credential pre-requisite
- Removed Supabase Client API key and Anon Key from environment-variables
- Removed Supabase as Tech stack from api<br />
Fixes #164 
No dependencies added
@rajdip-b 
___
documentation
___
- Removed Supabase from the technology stack in the API documentation.
- Removed Supabase API URL and Supabase ANON KEY from the environment variables documentation.
- Updated prerequisites documentation to no longer require a Supabase account.
___
<tr>
<td>
<details> …
> docs: Remove supabase from docs

- docs/contributing-to-keyshade/setting-things-up.md
This update modifies the project's setup documentation to replace the outdated NX setup instructions with the new Turbo setup instructions. This change reflects our shift to using Turbo for monorepo management, aligning the documentation with our current development practices.
Fixes #174
- No new dependencies introduced. The change is in documentation only.
@rajdip-b
**Relevant Files:**
|         | Relevant Files                                                                                                                |
|-----------------|-------------------------------------------------------------------------------|
| Documentation   |   <table>  <thead>   </tr>  </thead>  <tbody>  <tr>  <td><details><summary>##setting-things-up.md<br>`replace NX with Turbo in setup …
> docs(setup): replace NX with Turbo in setup instructions

- apps/web/src/components/colabEasy/index.tsx
- apps/web/src/components/shared/card/index.tsx
Fixed the issue where the “Approval before Commit” section was overflowing from the main grid. <br />
Fixes #177 
___
___
- Improved the layout and responsiveness of the "Collaboration made easy" section by transitioning to a grid layout and adjusting card components for better alignment.
- Introduced the ability to add custom styling to `Card` components through a new `className` prop, enhancing flexibility and customization.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td …
> fix(web): alignment issue in “Collaboration made easy” section

- apps/api/src/auth/service/auth.service.ts
- apps/api/src/common/create-user.ts
- apps/api/src/common/create-workspace.ts
- apps/api/src/prisma/migrations/20240413155927_add_default_workspace/migration.sql
- apps/api/src/prisma/schema.prisma
- apps/api/src/user/dto/create.user/create.user.ts
- apps/api/src/user/service/user.service.ts
- apps/api/src/user/user.e2e.spec.ts
- apps/api/src/workspace/dto/create.workspace/create.workspace.ts
- apps/api/src/workspace/service/workspace.service.ts
- apps/api/src/workspace/workspace.e2e.spec.ts
- docker-compose-test.yml
Creates a default workspace when a user is created. Default workspaces have these features:
- They have a `isDefault` flag set to true
- Owners are not allowed to leave the workspace or transfer its ownership 
Fixes #157
___
enhancement
___
- Introduced functionality to create a default workspace when a new user is created.
- Refactored user creation logic in AuthService and updated CreateUserDto to support optional fields.
- Added a new function for workspace creation with default workspace support and detailed logging.
- Enhanced user and workspace services to handle default workspaces, including preventing their deletion and ownership transfer.
- Updated e2e tests to cover new functionality and added cleanup utilities.
- Implemented a database migration to add an `isDefault` column to …
> feat(api): Create default workspace on user's creation

- apps/api/src/approval/controller/approval.controller.ts
- apps/api/src/common/alphanumeric-reason-pipe.spec.ts
- apps/api/src/common/alphanumeric-reason-pipe.ts
- apps/api/src/environment/controller/environment.controller.ts
- apps/api/src/project/controller/project.controller.ts
- apps/api/src/secret/controller/secret.controller.ts
- apps/api/src/variable/controller/variable.controller.ts
- apps/api/src/workspace/controller/workspace.controller.ts
- package.json
- pnpm-lock.yaml
Introduced a validation pipe for the reason field
Introduced two tests alongside this
Implemented the validation across 6 files
Fixes #161 
N/A
I dont think much can change about this, its a relatively simple process.
Photo of code passing test
- [X ] My PR follows the style guidelines of this project
- [X ] I have performed a self-check on my work
- [X ] My changes in code generate no new warnings
- [ X] I have added test cases to show that my feature works
- [X ] I have added relevant screenshots in my PR
- [X ] I have made the necessary updates to the documentation, or no documentation changes are required.
___
___
- Implemented `AlphanumericReasonValidationPipe` to ensure that the `reason` query parameter across various …
> feat(api): Added validation for reason field

- docs/contributing-to-keyshade/running-things-locally/running-the-api.md
API correction <br />
Fixes #186
@rajdip-b 
___
documentation
___
- Updated test descriptions to reflect the shift from integration tests to e2e tests.
- Modified the command for running unit tests to `pnpm run unit:api`.
- Streamlined the process for running e2e tests, eliminating the need for Docker setup and teardown commands.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
<tr>
<td>
<details>
<summary><strong>running-the-api.md</strong><dd><code>Update Test Descriptions and Commands in Documentation</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/contributing-to-keyshade/running-things-locally/running-the-api.md
<li>Updated the types of tests from …
> docs: Update running-the-api.md

- .env.example
- apps/api/src/auth/controller/auth.controller.ts
- apps/api/src/auth/service/auth.service.ts
- apps/api/src/common/create-user.ts
- apps/api/src/common/env/env.schema.ts
- apps/api/src/common/redirect.ts
- apps/api/src/common/set-cookie.ts
- apps/api/src/prisma/migrations/20240512141423_add_auth_provider/migration.sql
- apps/api/src/prisma/schema.prisma
- apps/api/src/user/service/user.service.ts
- apps/api/src/user/user.e2e.spec.ts
- Added redirect after oauth login/signup.
- Added `AuthProvider` enum to distinguish the kind of authentication the user made while signing up.
- Added checks to ensure that cross provider authentications are blocked.
___
___
- Enhanced OAuth handling in the authentication controller, including redirection and cookie setting.
- Updated authentication service to support multiple OAuth providers and prevent cross provider authentication.
- Added `AuthProvider` to user creation processes and updated relevant methods across services.
- Updated environment configurations and Prisma schema to support new OAuth functionalities.
___
<tr> …
> feat(api): Add OAuth redirection and polished authentication

- .github/workflows/release.yml
- package.json
- pnpm-lock.yaml
The error was happening because `npm` can't understand pnpm workspace. Refactoring it to `pnpx` worked, but with some tradeoffs.
- Installed the release deps in top level `package.json` as `devDependencies`
- Changed `npm` to `pnpm`
- Changed `npx` to `pnpx`
Fixes #171
___
enhancement
___
- Added necessary semantic release dependencies directly into `package.json` to manage versions and ensure compatibility.
- Simplified the installation process in the GitHub Actions workflow by using `pnpm i` which respects the lock file and installs all necessary dependencies.
- Updated the release command to use `pnpx` instead of `npx` to better integrate with the pnpm environment, addressing the issue where npm could not understand pnpm workspace.
___
<table><thead><tr><th></th><th …
> chore(release): Fix failing release

- apps/api/src/app/app.module.ts
- apps/api/src/auth/auth.module.ts
- apps/api/src/project/controller/project.controller.ts
- apps/api/src/project/project.e2e.spec.ts
- apps/api/src/project/service/project.service.ts
- apps/api/src/user/service/user.service.ts
___
- Simplified the import and configuration of `ConfigModule` in `app.module.ts`.
- Added a default value for `JWT_SECRET` in `auth.module.ts` to enhance robustness.
- Updated project fetching method in `project.controller.ts` and `project.service.ts` for clarity.
- Major enhancements and refactoring in project e2e tests, including better resource management and clearer test cases.
- Streamlined user creation process in `user.service.ts` to improve maintainability.
___
<tr>
<td>
<details>
<summary><strong>app.module.ts</strong><dd><code>Simplify ConfigModule Import and Remove Redundant Comment</code></dd></summary>
<hr> …
> test(api): Refactor project e2e tests to be more readable

- apps/api/src/api-key/controller/api-key.controller.ts
- apps/api/src/api-key/dto/create.api-key/create.api-key.ts
- apps/api/src/app/app.controller.ts
- apps/api/src/auth/controller/auth.controller.ts
- apps/api/src/environment/controller/environment.controller.ts
- apps/api/src/event/controller/event.controller.ts
- apps/api/src/feedback/controller/feedback.controller.ts
- apps/api/src/integration/controller/integration.controller.ts
- apps/api/src/main.ts
- apps/api/src/project/controller/project.controller.ts
- apps/api/src/secret/controller/secret.controller.ts
- apps/api/src/variable/controller/variable.controller.ts
- postman/collections/Integration Controller.json
- Removed the initialisation of the swagger docs from `main.ts`.
- Also removed all the tags for swagger docs which won't be required.
Fixes #218 
@rajdip-b 
___
enhancement, documentation
___
- Removed Swagger documentation and related decorators across multiple controllers and DTOs.
- Simplified API controllers by removing Swagger API documentation, which includes decorators like `ApiTags`, `ApiOperation`, and `ApiResponse`.
- Removed Swagger setup from the main application file, reducing complexity and potential security issues related to API documentation exposure.
___ …
> chore: Remove swagger docs

- apps/web/next.config.mjs
- apps/web/package.json
- apps/web/src/app/(main)/(mdx)/layout.tsx
- apps/web/src/app/(main)/(mdx)/privacy/page.mdx
- apps/web/src/app/(main)/(mdx)/terms_and_condition/page.mdx
- apps/web/src/components/shared/card/index.tsx
- apps/web/src/components/shared/footer/index.tsx
- apps/web/src/mdx-components.tsx
- pnpm-lock.yaml
Fixes #[ISSUENO]
___
enhancement
___
- Added custom MDX components for styled HTML tags in MDX files.
- Updated footer links to point to newly added legal pages (Terms and Conditions, Privacy Policy).
- Created a layout component for MDX pages to standardize page structure.
- Introduced new MDX content for Terms and Conditions and Privacy Policy.
- Configured MDX support in the Next.js configuration to handle MDX files.
- Added necessary MDX dependencies in `package.json`.
___
<table><thead><tr><th></th><th …
> feat(web): Add and link privacy and tnc page

- docs/contributing-to-keyshade/design-of-our-code/organization-of-code.md
FIX document typo from 'api' to 'web'
NIL
NIL
NIL
___
Documentation
___
- Corrected a typo in the `organization-of-code.md` file, changing the label from `api` to `web` for the web application.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
<tr>
<td>
<details>
<summary><strong>organization-of-code.md</strong><dd><code>Fix typo in the organization-of-code documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/contributing-to-keyshade/design-of-our-code/organization-of-code.md
<li>Corrected a typo in the description of the web application.<br> <li> Changed the label from <code>api</code> to <code>web</code> for the web …
> docs: Fix typo in organization-of-code.md

- apps/api/src/auth/service/auth.service.ts
Replaced RandomUUid with Math.Random <br />
Fixes #211 
___
enhancement
___
- Updated OTP generation method in `auth.service.ts` to generate numeric codes using `Math.random()` instead of alphanumeric codes with `randomUUID()`.
- This change affects both the creation and updating of OTP codes.
___
<tr>
<td>
<details>
<summary><strong>auth.service.ts</strong><dd><code>Change OTP Generation to Use Numeric Codes</code>&nbsp; &nbsp; &nbsp; …
> refactor(api): Replaced OTP code from alphanumeric to numeric

- apps/api/src/auth/guard/auth/auth.guard.ts
- apps/api/src/common/env/env.schema.ts
- apps/api/src/user/service/user.service.ts
Email regex validation added. 
z.string().regex(/^[a-zA-Z0-9._%+-]+ [<][a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}
In this single line, the regex pattern is directly embedded in the schema definition. This keeps the code concise and straightforward. (Expected format is "your-name <your-name@email.com>")
<br />
Fixes #216 
> chore(api): Fix inconsistencies in zod schema

- apps/api/src/workspace-role/workspace-role.e2e.spec.ts
- apps/api/src/workspace/workspace.e2e.spec.ts
Tests, Enhancement
___
- Refactored the `workspace-role.e2e.spec.ts` to use `UserService` for user creation, improving test setup and teardown with `beforeEach` and `afterEach` hooks.
- Removed direct Prisma calls for user and workspace creation in `workspace-role.e2e.spec.ts`.
- Updated test cases in `workspace-role.e2e.spec.ts` to align with the new setup.
- Removed `cleanUp` import and call in `afterAll` in `workspace.e2e.spec.ts`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests
<tr>
<td>
<details>
<summary><strong>workspace-role.e2e.spec.ts</strong><dd><code>Refactor workspace role e2e tests for improved setup</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> test: Refactor workspace role e2e tests

- package.json
Added docker build and run commands._ <br />
Fixes #257 
> chore: Added docker build and run commands to` package.json`

- .github/workflows/deploy-web.yml
- .github/workflows/pr-lint.yaml
- .github/workflows/release.yml
- .github/workflows/validate-api.yaml
- .github/workflows/validate-web.yaml
_Updated Github Action plugin versions to the latest ones_ <br />
Fixes #262 
> chore: Update GitHub Action plugin versions 

- apps/api/src/secret/secret.e2e.spec.ts
- apps/api/src/secret/secret.types.ts
- apps/api/src/secret/service/secret.service.ts
- apps/api/src/variable/service/variable.service.ts
- apps/api/src/variable/variable.e2e.spec.ts
- apps/api/src/variable/variable.types.ts
Updated return type while fetching secrets and variables <br />
Fixes #261
> refactor(api): Update return type while fetching secrets and variables

- apps/api/src/secret/service/secret.service.ts
…bulk fetch
Replace for loop with array indexing while decrypting secrets during bulk fetch <br />
Fixes #265 
___
Enhancement
___
- Replaced the for loop with array indexing to optimize the decryption of secrets during bulk fetch.
- Simplified the decryption logic by assuming only the first version of each secret needs to be decrypted.
___
<tr>
<td>
<details>
<summary><strong>secret.service.ts</strong><dd><code>Optimize secret …
> refactor(api): Replace for loop with array indexing while decrypting secrets during bulk fetch #265

- docs/SUMMARY.md
- docs/cli/init.md
- docs/cli/introduction.md
- docs/cli/profile.md
- docs/cli/run.md
- docs/contributing-to-keyshade/design-of-our-code/organization-of-code.md
- docs/contributing-to-keyshade/environment-variables.md
- docs/internals/architecture-of-keyshade.md
- docs/internals/how-the-cli-works.md
Documentation
___
- Added comprehensive documentation for the CLI tool, including commands like `init`, `profile`, and `run`.
- Updated the table of contents to include new CLI sections and moved the architecture section under Internals.
- Fixed image paths in the architecture documentation.
- Added a new environment variable `NEXT_PUBLIC_BACKEND_URL` to the environment variables documentation.
- Provided detailed explanations of the internal workings of the CLI, including configuration files.
___
<tr>
<td>
<details>
<summary><strong>SUMMARY.md</strong><dd><code>Updated table of contents with CLI and Internals sections.</code></dd></summary>
<hr> …
> docs(cli): Added usage docs

- apps/cli/src/commands/base.command.ts
- apps/cli/src/commands/profile/create.profile.ts
- apps/cli/src/commands/profile/delete.profile.ts
- apps/cli/src/commands/profile/list.profile.ts
- apps/cli/src/commands/profile/update.profile.ts
- apps/cli/src/commands/profile/use.profile.ts
- apps/cli/src/util/profile.ts
Enhancement, Bug fix
___
- Refactored profile-related commands to improve readability and maintainability.
- Added utility functions for profile operations: `checkProfileExists`, `checkIsDefaultProfile`, and `getDefaultProfile`.
- Improved error handling and code structure in profile commands.
- Renamed methods for better clarity and consistency.
___
<tr>
<td>
<details>
<summary><strong>base.command.ts</strong><dd><code>Refactor profile default retrieval in BaseCommand</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
apps/cli/src/commands/base.command.ts
<li>Added <code>getDefaultProfile</code> import.<br> <li> Replaced …
> refactor(cli): Refactored profile commands into readable blocks

- apps/api/src/common/paginate.spec.ts
- apps/api/src/common/paginate.ts
Added common/paginate.ts and common/paginate.spec.ts under api. 
The paginate method takes totalCount, realtiveUrl, query and defaultQuery.
- The `totalCount` is usually calculated by the calling method using prisma.[table].count() without any filters like page and limit.
- `relativeUrl` is the the endpoint for a service function. Eg: `/workspace-role/${workspaceId}/all`
- `query` belongs to QueryOptions necessary to do pagination and `defaultQuery` are extra queries that could be provided.
Fixes #345
1 Test Suite and 4 Test Cases are added.
Passes paginate unit tests.
> feat(api): Create a paginate method

- .github/workflows/auto-assign.yaml
>  Whenever someone uses /attempt on any issue, the GitHub action pipeline in auto-assign.yml assigns the commenter the issue. If the issue has any project associated with it, we would like to change its current status to "In Progress". An issue might have 0 to n number of projects assigned to it, we would like auto-assign.yml to be updated in a way to change the status of all these projects.
Feature implemented in PR.
Fixes #316
N/A
N/A
@rajdip-b 
N/A
> feat(chore): Update auto-assign.yaml

- apps/api/src/common/create-user.ts
- apps/api/src/user/user.e2e.spec.ts
Skip workspace creation when user is admin
Fixes #191 
N/A
N/A
@rajdip-b 
N/A
> chore(API): Skip workspace creation when user is admin

- apps/api/src/project/project.e2e.spec.ts
- apps/api/src/project/service/project.service.ts
- Add support for paginated response in `getProjectsOfWorkspace()` and `getAllProjectForks()` of project.service.ts under API.
- Add and improve required tests.
- Hard-coded page and limit, to be more strict in tests.
Fixes #338
Fixes #369 , since pagination is dependant on totalCount, therefore checking authority for all project might be a good option.
- Explicit number conversion in prisma query as well as in paginate's arguments could be ignored.
Some tests:
> feat(api): Add pagination metadata to Project module

- apps/api/src/integration/controller/integration.controller.ts
- apps/api/src/integration/integration.e2e.spec.ts
- apps/api/src/integration/service/integration.service.ts
- Add paginated metadata response support for `getAllIntegrationsOfWorkspace()` of integration.service.ts under API
- Add extra test case
- Fix e2e test not working for `getAllIntegrations()` Controller.
Fixes #343 
N/A
E2E tests failure due to default page set to 1:
> feat(api): Add pagination metadata to Integration module

- apps/api/src/variable/service/variable.service.ts
- apps/api/src/variable/variable.e2e.spec.ts
- Paginated response support for `getAllVariablesOfProject()` for variable.service.ts under API.
- Updated test cases to reflect the reponse.
Fixes #342 
N/A
Glance of metadata checks:
> feat(api): Add pagination metadata to Variable module

- apps/api/src/app/app.module.ts
- apps/api/src/auth/auth.module.ts
- apps/api/src/auth/controller/auth.controller.spec.ts
- apps/api/src/auth/guard/auth/auth.guard.spec.ts
- apps/api/src/auth/guard/auth/auth.guard.ts
- apps/api/src/auth/service/auth.service.spec.ts
- apps/api/src/auth/service/auth.service.ts
- apps/api/src/cache/cache.module.ts
- apps/api/src/cache/cache.service.spec.ts
- apps/api/src/cache/cache.service.ts
- pnpm-lock.yaml
_Creates a new `cache` module for setting and getting redis cache and using it in auth guard_ <br />
Fixes #207
> feat(api): Add user cache for optimization

- apps/api/src/secret/secret.e2e.spec.ts
- apps/api/src/secret/service/secret.service.ts
-  Add pagination metadata support for `getAllSecretsOfProject()` in secret.service.ts under API.
- Add test cases for metadata checks.
Fixes #341 
N/A
One of the test case:
> feat(api): Add pagination metadata to Secret module

- apps/api/src/workspace/service/workspace.service.ts
- apps/api/src/workspace/workspace.e2e.spec.ts
- `getAllMembersOfWorkspace()` and `getWorkspacesOfUser()` in workspace.service.ts under api, now supports paginated outputs
- Modify 2 e2e tests and add 1 e2e test
Fixes #339
N/A
An extra e2e test for workspace module for varying page and limit params.
> feat(api): Add pagination metadata to Workspace module 

- apps/api/src/environment/environment.e2e.spec.ts
- apps/api/src/event/event.e2e.spec.ts
- apps/api/src/event/service/event.service.ts
- apps/api/src/project/project.e2e.spec.ts
- apps/api/src/secret/secret.e2e.spec.ts
- apps/api/src/variable/variable.e2e.spec.ts
- apps/api/src/workspace-role/workspace-role.e2e.spec.ts
- apps/api/src/workspace/workspace.e2e.spec.ts
- Add support for paginated response for `getEvents()` of event.service.ts under API.
- Add and improve relevant test cases.
- Modify event variable's value in affected modules' e2e, where state of events are queried.
Fixes #344
Also, Fixes #336 after merging this and #382 #387 #388 #389 #390 #391 #393.
N/A
N/A
Extra test:
> feat(api): Add pagination metadata to Event module

- apps/cli/src/http/auth.ts
- apps/cli/src/http/secret.ts
- apps/cli/src/http/variable.ts
The following files contained objects of the controller call implementation and I have converted the objects to classes made the functions static, and exported the instance of the class.
Fixes #299 
_Mention any improvements to be done in the future related to any file/feature_
___
Enhancement
___
- Converted `AuthController`, `SecretController`, and `VariableController` objects to classes.
- Made the main methods in each controller (`checkApiKeyValidity`, `fetchSecrets`, `fetchVariables`) static.
- Exported instances of the newly created classes.
___ …
> chore(cli): Changed objects to classes

- apps/api/src/secret/controller/secret.controller.ts
- apps/api/src/secret/secret.e2e.spec.ts
- apps/api/src/secret/service/secret.service.ts
Create endpoint for fetching all revisions of a secret
```http
GET /api/secret/:secretId/revisions/:environmentId 
```
<br />
Fixes #272 
___
___
- Added a new endpoint `GET /api/secret/:secretId/revisions/:environmentId` to fetch all revisions of a secret.
- Implemented the `getRevisionsOfSecret` method in the `SecretController` class.
- Added `getRevisionsOfSecret` method to the `SecretService` class, including authority checks and retrieval logic.
- Added end-to-end tests for the new endpoint, covering multiple scenarios including fetching multiple …
> feat(api): Create endpoint for fetching all revisions of a secret

- apps/api/src/variable/controller/variable.controller.ts
- apps/api/src/variable/service/variable.service.ts
- apps/api/src/variable/variable.e2e.spec.ts
Adds a getRevisionsOfVariable method to get revisions of a variable <br />
Fixes #271 
- [ x] My PR follows the style guidelines of this project
- [x ] I have performed a self-check on my work
___
___
- Added a new endpoint `getRevisionsOfVariable` to fetch revisions of a variable with pagination support.
- Implemented the corresponding method in the service layer with necessary authority checks.
- Added end-to-end tests for the new endpoint covering multiple scenarios including no revisions, non-existent variable/environment, and access control.
___ …
> feat(api): Create endpoint for fetching all revisions of a variable

- packages/api-client/src/controllers/event/event.ts
- packages/api-client/src/types/event.types.d.ts
- packages/api-client/tests/event.spec.ts
controller for Event module<br />
Fixes #356 
___
___
- Created `EventController` class with `getEvents` method to fetch events based on request parameters.
- Defined `GetEventsRequest` and `GetEventsResponse` interfaces for type safety.
- Added comprehensive tests for `EventController` covering various event sources such as project, environment, secret, and variable.
___
<tr>
<td>
<details> …
> feat(api-client): Create controller for Event module

- docs/contributing-to-keyshade/running-things-locally/api-testing.md
Minor typo fix in doc regarding postman workspace link
___
documentation
___
- Fixed a minor typo in the documentation regarding the Postman workspace link by removing an extra 'h' from the URL.
___
<tr>
<td>
<details>
<summary><strong>api-testing.md</strong><dd><code>Fix typo in Postman workspace link in documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/contributing-to-keyshade/running-things-locally/api-testing.md
<li>Corrected a typo in the Postman workspace link.<br> <li> Removed an extra 'h' from the URL.<br>
</details>
</td>
<td><a href="https://github.com/keyshade-xyz/keyshade/pull/411/files#diff-d481a23b147b6 …
> docs: Fixed minor typo in postman workspace link

- apps/platform/src/app/(main)/page.tsx
- apps/platform/src/app/(main)/project/[project]/@secret/page.tsx
- apps/platform/src/app/(main)/project/[project]/layout.tsx
- apps/platform/src/app/auth/invite/page.tsx
- apps/platform/src/components/shared/navbar/index.tsx
- apps/platform/src/components/teams/teamTable/index.tsx
- apps/platform/src/components/ui/line-tab.tsx
- apps/platform/src/env.ts
- apps/platform/src/lib/workspace-storage.ts
- apps/platform/src/middleware.ts
- package.json
Added optional chaining in platform code due to strict null check implementation
Fixes #412
___
___
- Added optional chaining across multiple files to handle potential null or undefined values safely.
- Implemented checks for `localStorage` to prevent errors in environments where it is not available.
- Updated `package.json` to include `@keyshade/api-client` in dependencies.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>10 files</summary><table>
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Add localStorage check and optional chaining</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> chore(platform): Added optional chaining due to strict null check

- .gitignore
- apps/api/src/user/service/user.service.ts
- apps/api/src/user/user.e2e.spec.ts
- packages/eslint-config-custom/package-lock.json
- packages/tsconfig/package-lock.json
Added default workspace details in `getSelf` function for a user
Fixes #365 
Sample response after updating should be like this
```{
"id": "cm0s8xc1y000013zv8gextk2n",
"email": "regularuser@gmail.com",
"name": null,
"profilePictureUrl": null,
"isActive": true,
"isOnboardingFinished": false,
"isAdmin": false,
"authProvider": "EMAIL_OTP",
"defaultWorkspace": {
"id": "713d0227-eb11-4228-961a-ff7d5d707471",
"name": "My Workspace",
"description": null,
"isFreeTier": true,
"createdAt": "2024-09-07T14:34:15.256Z",
"updatedAt": "2024-09-07T14:34:15.256Z",
"lastUpdatedById": null
}
}
```
___
___
- Enhanced the `getSelf` function to include default workspace details for non-admin users.
- Updated end-to-end tests to verify the inclusion of `defaultWorkspace` in the user response. …
> feat(API): Included default workspace details in getSelf function

- apps/api/src/api-key/service/api-key.service.ts
Error messages updated in `keyshade/apps/api/src/api-key/service/api-key.service.ts` file<br />
Fixes #417
___
Bug fix
___
- Updated error messages in the `ApiKeyService` to provide clearer and more accurate information by using `apiKeySlug` instead of `apiKeyId`.
- Ensured consistency in error handling across methods in the `ApiKeyService`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>api-key.service.ts</strong><dd><code>Fix error messages in …
> fix: Error messages fixed in api-key service

- apps/platform/src/app/(main)/project/[project]/@secret/page.tsx
- apps/platform/src/components/ui/skeleton.tsx
Implemented the shadcn/ui skeleton to render a loader while fetching secrets from the server in the secrets page.
Fixes #322 
[shadcn/ui-Skeleton](https://ui.shadcn.com/docs/components/skeleton)
https://github.com/user-attachments/assets/282a0f35-4509-4e58-ba44-665f3badd849
___
enhancement
___
- Introduced a loading skeleton on the secrets page to improve user experience while data is being fetched.
- Created a new `Skeleton` component for consistent loading animations across the application.
- Managed loading state using a boolean `isLoading` and displayed skeleton loaders conditionally.
- Enhanced the UI by providing visual feedback during data …
> feat(platform): Add loading skeleton in the secrets page

- apps/api/src/app/app.module.ts
- apps/api/src/auth/auth.types.ts
- apps/api/src/auth/guard/auth/auth.guard.ts
- apps/api/src/auth/service/auth.service.ts
- apps/api/src/cache/cache.service.ts
- apps/api/src/common/user.ts
- apps/api/src/common/util.ts
- apps/api/src/decorators/user.decorator.ts
- apps/api/src/user/controller/user.controller.ts
- apps/api/src/user/service/user.service.ts
- apps/api/src/user/user.e2e.spec.ts
- apps/api/src/user/user.types.ts
- apps/api/src/workspace-membership/service/workspace-membership.service.ts
- apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
- apps/api/src/workspace/dto/create.workspace/create.workspace.ts
- apps/api/src/workspace/service/workspace.service.ts
- packages/api-client/src/controllers/workspace.ts
- packages/api-client/src/index.ts
- packages/api-client/src/types/workspace.types.d.ts
- packages/api-client/tests/config/setup.ts
- packages/api-client/tests/workspace.spec.ts
Fixes #348 
Added the controllers for workspace.
> feat(api-client): Added workspace controller

- apps/api/src/common/workspace.ts
- apps/api/src/event/event.e2e.spec.ts
- apps/api/src/prisma/migrations/20240915122629_add_icon_remove_description_from_workspace/migration.sql
- apps/api/src/prisma/schema.prisma
- apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
- apps/api/src/workspace/dto/create.workspace/create.workspace.ts
- apps/api/src/workspace/service/workspace.service.ts
- apps/api/src/workspace/workspace.e2e.spec.ts
- packages/api-client/src/types/workspace.types.d.ts
- packages/api-client/tests/workspace.spec.ts
- packages/schema/src/workspace.ts
Added icon and removed description field from workspace
Fixes #229 
- [] Postman updation
Sample response for fetching all workspace of a user
``` {
"id": "006bd5bf-43ac-41ad-b7a9-b1317d08f8ee",
"name": "My first workspace 2",
"slug": "my-first-workspace-2-0",
"isFreeTier": true,
"createdAt": "2024-09-15T13:32:58.131Z",
"updatedAt": "2024-09-15T13:32:58.131Z",
"ownerId": "cm0v65bm00000130sigtvry7y",
"isDefault": false,
"icon": "🤓",
"lastUpdatedById": null
},
```
Request Body for creating a new Workspace 
```{
"name": "My first workspace 2",
"icon":"🤓"
}
```
___
___
- Replaced the `description` field with an `icon` field in the workspace model, affecting creation and update operations.
- Updated database schema and migration scripts to reflect the removal of …
> feat(API):  Added icon and removed description field from workspace

- apps/api/src/common/env/env.schema.ts
Added prod env schema in env file
Fixes #357
___
enhancement
___
- Introduced a new `prodSchema` to define environment variables for the production environment, ensuring all necessary variables are validated.
- Renamed `generalSchema` to `devSchema` to better reflect its purpose.
- Updated the `EnvSchemaType` to infer from the newly added `prodSchema`.
- Included the `prodSchema` in the `EnvSchema` discriminated union to support multiple environment configurations.
___
<tr>
<td>
<details>
<summary><strong>env.schema.ts</strong><dd><code>Add production environment schema and update type inference</code></dd></summary>
<hr> …
> feat(api): Add prod env schema in env file

- apps/web/src/components/colabEasy/index.tsx
- apps/web/src/components/lifeEasySection/index.tsx
- apps/web/src/components/secretSection/index.tsx
The website had a horizontal scroll bar when changing to different screen sizes. The tailwind breakpoints were not used properly in my opinion. So I added some more breakpoints so it becomes more responsive as some cards in the page are pushing the beyond the View port. There were two options, either tweak the width of the cards or change the grid layout. Changing the width of the cards making elements look bad in other sections of the page and is overall not a good idea as card is a reusable component. So I changed the parent container div layout. On desktop screen it will be 3, on tablet size it will be 2. I didn't touched the mobile responsive design.
Video- 
https://github.com/user-attachments/assets/47d9e64a-634f-4d85-933c-c0ba0def965f
Fixes #437 
_Mention any dependencies/packages …
> fix(web): Horizontal Scrolling issue on the website

- apps/web/src/components/shared/footer/index.tsx
I fixed the issue where the website name in the footer was either partially displayed or overlapped with other elements. The website name is now fully visible and responsive, regardless of the screen size.
Fixes #433
No additional dependencies or packages were used for this fix.
___
bug_fix
___
- Fixed the issue where the footer website name was cut-off or overlapped by un-commenting and properly wrapping the `FooterLogoSVG` component.
- Ensured the `FooterLogoSVG` is displayed with appropriate padding to prevent …
> fix: resolve footer website name cut-off or overlap issue

- apps/api/src/workspace/service/workspace.service.ts
- apps/api/src/workspace/workspace.e2e.spec.ts
Changed the exportData function in the workspace controller to no longer return project IDs. I updated the e2e test to now check for the important fields that are supposed to be returned by exportData.
Fixes #425
None
The test currently doesn't test if there is extra fields that is not needed/not supposed to be there, only that the important fields are there. If necessary, I will change the test to be more precise.
___
___
- Removed project IDs from the `exportData` function in the workspace …
> feat: Remove project IDs from workspace role export data and update tests

- apps/api/src/project/controller/project.controller.ts
- apps/api/src/project/dto/fork.project/fork.project.ts
- apps/api/src/workspace-role/service/workspace-role.service.ts
- apps/cli/package.json
- apps/cli/src/commands/base.command.ts
- apps/cli/src/commands/project.command.ts
- apps/cli/src/commands/project/create.project.ts
- apps/cli/src/commands/project/delete.project.ts
- apps/cli/src/commands/project/fork.project.ts
- apps/cli/src/commands/project/get.project.ts
- apps/cli/src/commands/project/list-forks.project.ts
- apps/cli/src/commands/project/list.project.ts
- apps/cli/src/commands/project/sync.project.ts
- apps/cli/src/commands/project/unlink.project.ts
- apps/cli/src/commands/project/update.project.ts
- apps/cli/src/commands/scan.command.ts
- apps/cli/src/commands/workspace/list.workspace.ts
- apps/cli/src/index.ts
- apps/cli/src/types/command/command.types.d.ts
- packages/api-client/src/controllers/project.ts
- packages/api-client/src/types/project.types.d.ts
- packages/api-client/src/types/workspace-role.types.d.ts
- packages/api-client/tests/project.spec.ts
- packages/api-client/tests/workspace-role.spec.ts
Fixes #298
___
enhancement
___
- Introduced a new `ProjectCommand` class with various subcommands for managing projects, including create, delete, fork, get, list, sync, unlink, and update operations.
- Refactored `ScanCommand` to utilize the `Logger` for logging instead of direct console output, improving consistency and maintainability.
- Integrated the `ProjectCommand` into the CLI command list, enabling project management functionalities.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>12 files</summary><table>
<tr>
<td>
<details>
<summary><strong>project.command.ts</strong><dd><code>Add `ProjectCommand` class with subcommands for project management</code></dd></summary>
<hr> …
> feat(cli): Add project command

- apps/api/src/workspace/service/workspace.service.ts
- packages/api-client/src/types/workspace.types.d.ts
Updated the response of the global search API with slug instead of id.
Fixes #426 
___
Bug fix
___
- Updated the global search API to return `slug` instead of `id` in the response.
- Modified multiple query methods in `WorkspaceService` to select `slug` instead of `id`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>workspace.service.ts</strong><dd><code>Replace `id` with `slug` in global search queries</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix(api): Replace the id with slug in the global-search service

- docs/cli/scan.md
This PR adds documentation for the new `scan` feature in the CLI, providing users with clear instructions on how to utilize this functionality effectively. <br />
Fixes #459 
Consider adding examples for common use cases of the `scan` feature in future documentation updates.
@rajdip-b 
N/A
___
Documentation
___
- Added comprehensive documentation for the new `scan` command in the CLI.
- Provided usage instructions and detailed options for scanning files.
- Aimed to help users detect hardcoded secrets in project files effectively.
___
<tr>
<td>
<details> …
> docs: Add documentation for scan in CLI

- docs/cli/environment.md
This PR adds documentation for the new environment feature in the CLI, providing users with clear instructions on how to utilize this functionality effectively.
Fixes #457 
Consider adding examples for common use cases of the scan feature in future documentation updates.
@rajdip-b 
N/A
___
Documentation
___
- Added a new documentation file for the `environment` command in the Keyshade CLI.
- Documented subcommands including `create`, `delete`, `get`, `list`, and `update`.
- Provided detailed usage instructions, arguments, and options for each subcommand.
- Enhanced user understanding of managing environments within Keyshade.
___ …
> docs: Add documentation for environment in CLI

- docs/cli/workspace.md
This PR adds documentation for the `workspace` feature in the CLI, providing users with clear instructions on how to utilize this functionality effectively. <br />
Fixes #458 
Possibly adding examples for common use cases of the `workspace` feature in future documentation updates.
@rajdip-b
N/A
___
Documentation
___
- Added detailed documentation for the `workspace` command in the CLI, including descriptions and usage examples for subcommands such as `create`, `delete`, `export`, `get`, `list`, `search`, and `update`.
- Provided comprehensive details on command arguments and options to guide users in managing workspaces effectively.
___ …
> docs: Adding documentation for  cli command

- docs/contributing-to-keyshade/running-things-locally/docker-support.md
Added `docker-support.md` to facilitate a designated space for docker documentation <br />
Fixes #279 
None.
Expand when new docker features are implemented for the project.
@rajdip-b 
N/A
___
Documentation
___
- Added a new documentation file `docker-support.md` to provide detailed instructions on building and running applications using Docker.
- Included prerequisites for Docker installation and usage.
- Provided specific commands for building and running the Web Application, API, and Platform using Docker.
- Detailed port usage and environment variable requirements.
- Instructions for starting and stopping services using Docker Compose.
___ …
> docs: Added docker support documentation

- apps/cli/src/commands/workspace.command.ts
- apps/cli/src/commands/workspace/role.workspace.ts
- apps/cli/src/commands/workspace/role/delete.role.ts
- apps/cli/src/commands/workspace/role/get.role.ts
- apps/cli/src/commands/workspace/role/list.role.ts
- apps/cli/src/commands/workspace/role/update.role.ts
I have made 4 commands that are sub-commands of `role`. the commands are `get`, `list`, `update`, and `delete`. Update has the ability to change name, description, color code, authorities, and projects.  
Fixes #447
N/A
The authorities and projects are updated poorly. If a role has a few authorities already, and you need to add a new one, you have to give the command the entire list of all authorities you already have + the authorities you need. Same for projects. This is tedious, arduous, and annoying. If possible and applicable, in the future there should be another sub-command for project and for authorities. …
> feat(cli): implement commands to get, list, update, and delete, workspace roles

- docs/SUMMARY.md
- docs/contributing-to-keyshade/running-things-locally/running-the-platform.md
This PR adds documentation for the running the platform.
Fixes #472 
N/A
@rajdip-b 
N/A
___
Documentation
___
- Added a new section in the documentation for running the platform locally.
- Updated the summary to include a link to the new "Running the Platform" documentation.
- Provided detailed instructions on setting up, running, and testing the platform app using NextJS and TypeScript.
- Included information on how to view the platform app in a browser.
___
<tr>
<td>
<details>
<summary><strong>SUMMARY.md</strong><dd><code>Add "Running the Platform" to documentation …
> docs: Added documentation for running the platform

- apps/cli/src/commands/environment/create.environment.ts
- apps/cli/src/commands/environment/delete.environment.ts
- apps/cli/src/commands/environment/get.environment.ts
- apps/cli/src/commands/environment/list.environment.ts
- apps/cli/src/commands/environment/update.environment.ts
Updated controller invocation in environment commands in 
keyshade/apps/cli/src/commands/environment/list.environment.ts
Fixes #443 
@rajdip-b 
___
enhancement
___
- Refactored the environment fetching logic to use a centralized `ControllerInstance` instead of directly instantiating `EnvironmentController`.
- Simplified headers management by utilizing `this.headers` within the command.
___
<tr>
<td>
<details>
<summary><strong>list.environment.ts</strong><dd><code>Refactor environment fetching to use ControllerInstance</code>&nbsp; &nbsp; </dd></summary>
<hr>
apps/cli/src/commands/environment/list.environment.ts …
> chore: Update controller invocation in environment commands

- apps/web/src/components/hero/index.tsx
Now if the user email gets waitlisted then the email field will be cleared for better user experience.
Related to #474 
@rajdip-b 
___
enhancement
___
- Fixed a typo in the error message displayed when the email field is empty.
- Enhanced user experience by clearing the email input field after the email is successfully waitlisted.
___
<tr>
<td>
<details>
<summary><strong>index.tsx</strong><dd><code>Improve user experience by clearing email field post-waitlisting</code></dd></summary>
<hr>
apps/web/src/components/hero/index.tsx
<li>Fixed a typo in the error message for empty email input.<br> <li> Added functionality to …
> chore: Clearing email field after waitlisting the user email

- packages/api-client/src/controllers/user.ts
- packages/api-client/src/types/user.types.d.ts
- packages/api-client/tests/user.spec.ts
API-CLIENT: Create controller for User module <br />
Fixes #349
None
___
___
- Implemented a new `UserController` class to manage user-related operations such as retrieving, updating, and deleting user data.
- Defined TypeScript interfaces for user-related requests and responses, including operations for email change OTP validation and resending.
- Added comprehensive tests for the `UserController` methods to ensure correct functionality of user operations.
___ …
> feat(api): API-CLIENT: Create controller for User module

- apps/web/package.json
- apps/web/src/components/hero/index.tsx
- pnpm-lock.yaml
Implemented email validation using Zod.
Related to #463 
@rajdip-b @kriptonian1
___
enhancement, dependencies
___
- Implemented email validation in the Hero component using the Zod library to ensure valid email addresses are entered.
- Updated the toast message to prompt users to enter a valid email address.
- Added the Zod library to the project's dependencies in `package.json`.
- Updated the `pnpm-lock.yaml` file to reflect the addition of the Zod library and other dependency updates.
___
<tr>
<td>
<details>
<summary><strong>index.tsx</strong><dd><code>Implement email validation in Hero component</code>&nbsp; &nbsp; …
> chore: Email validation

- docs/contributing-to-keyshade/running-things-locally/running-the-api.md
Added a command `pnpm run db:reset` to the documentation for resetting the local Prisma database. This helps contributors start fresh when testing locally or troubleshooting. The change is included in the "Running the API" section. <br />
Fixes #495
___
Documentation
___
- Added documentation on how to reset the local Prisma database using the command `pnpm run db:reset`.
- This addition helps contributors start with a clean database state for testing and troubleshooting.
- The new instructions are included in the "Running the API" section of the documentation.
___
<tr>
<td>
<details> …
> docs: Add instructions for resetting the local Prisma database (#495)

- apps/cli/.eslintrc.cjs
- apps/cli/src/commands/secret.command.ts
- apps/cli/src/commands/secret/create.secret.ts
- apps/cli/src/commands/secret/delete.secret.ts
- apps/cli/src/commands/secret/get.secret.ts
- apps/cli/src/commands/secret/list.secret.ts
- apps/cli/src/commands/secret/revisions.secret.ts
- apps/cli/src/commands/secret/rollback.secret.ts
- apps/cli/src/commands/secret/update.secret.ts
- apps/cli/src/index.ts
Add functionality to operate on Secrets<br />
Fixes #302 
___
Enhancement
___
- Added a new `SecretCommand` class to manage secrets via CLI, including subcommands for creating, deleting, listing, fetching, updating, and rolling back secrets.
- Implemented `CreateSecret`, `DeleteSecret`, `GetSecret`, `ListSecret`, `FetchSecretRevisions`, `RollbackSecret`, and `UpdateSecret` classes, each handling specific secret operations.
- Registered `SecretCommand` in the CLI command list to enable secret management functionality.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details> …
> feat(cli): Add functionality to operate on Secrets

- apps/api/src/secret/secret.e2e.spec.ts
- apps/api/src/secret/secret.types.ts
- apps/api/src/secret/service/secret.service.ts
- packages/api-client/src/types/secret.types.d.ts
- packages/api-client/tests/secret.spec.ts
Add environmentSlug in multiple places across the secret module <br />
Fixes #486 
___
___
- Enhanced the secret module to include `environmentSlug` alongside `environmentId` in various places.
- Updated the secret service to select and return both `id` and `slug` for environments.
- Modified API client types to reflect the inclusion of `environment` details in secret versions.
- Added and updated tests in both the API and API client to verify the presence of `environment.id` and `environment.slug`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>secret.e2e.spec.ts</strong><dd><code>Add tests for environment slug …
> fix(api,api-client): Add environmentSlug in multiple places across the secret module

- apps/cli/src/commands/variable.command.ts
- apps/cli/src/commands/variable/create.variable.ts
- apps/cli/src/commands/variable/delete.variable.ts
- apps/cli/src/commands/variable/list.variable.ts
- apps/cli/src/commands/variable/revisions.variable.ts
- apps/cli/src/commands/variable/rollback.variable.ts
- apps/cli/src/commands/variable/update.variable.ts
- apps/cli/src/index.ts
Add functionality to operate on Variables <br />
Fixes #301 
___
Enhancement
___
- Added a new `VariableCommand` class to manage variables through the CLI, including subcommands for creating, deleting, listing, fetching revisions, rolling back, and updating variables.
- Implemented individual command classes for each variable operation, defining necessary arguments and options.
- Integrated the `VariableCommand` into the CLI application, making it available for use.
___
<tr>
<td>
<details>
<summary><strong>variable.command.ts</strong><dd><code>Add `VariableCommand` class for CLI variable operations</code>&nbsp; &nbsp; …
> feat(cli): Add functionality to operate on Variables

- .github/workflows/validate-secret-scan.yaml
- codecov.yml
- packages/secret-scan/.mocharc.json
- packages/secret-scan/jest.config.ts
- packages/secret-scan/package.json
- packages/secret-scan/src/test/secret.test.ts
- packages/secret-scan/tsconfig.json
- packages/secret-scan/tsconfig.spec.json
- pnpm-lock.yaml
_This PR fixes a test coverage-related issue in the `secret-scan package` by migrating from Mocha to Jest for improved test execution and flexibility. The changes include:_ <br />
- Replacing Mocha configuration with Jest.
- Updating the workflow configuration(`validate-secret-scan.yaml`).
- Adding secret-scan flag on `codecov.yml`. <br/>
Fixes #521 
- [✅] My PR follows the style guidelines of this project
- [✅] I have performed a self-check on my work
- [✅] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [✅] My changes in code generate no new warnings
___
Tests, Enhancement
___
- Migrated the `secret-scan` package tests from Mocha to Jest for improved test execution and flexibility.
- Added Jest …
> test(secret-scan): Add test coverage

- apps/cli/src/commands/base.command.ts
- apps/cli/src/commands/profile/create.profile.ts
- apps/cli/src/commands/profile/list.profile.ts
- apps/cli/src/commands/profile/update.profile.ts
- apps/cli/src/types/index.types.d.ts
- `index.types.d.ts`: Added `metrics_enabled` boolean to the ProfileConfig.
- `create.profile.ts`: Introduced `-m, --enable-metrics` for enabling/disabling metrics collection.
- `update.profile.ts`: Added the flag to update the metrics collection status.
- `list.profile.ts`: Displayed `Metrics Enabled` column in the profile table
- `base.command.ts`: Added `metricsEnabled` to store and manage the metrics setting.
Fixes #528 
- [✅] My PR follows the style guidelines of this project
- [❌] I have performed a self-check on my work
___
Enhancement
___
- Added a `metrics_enabled` key to the `ProfileConfig` interface to support metrics collection.
- Introduced `--enable-metrics` flag in `create.profile.ts` for enabling/disabling metrics during profile creation.
- Updated `update.profile.ts` to …
> feat(cli): Store `metrics_enabled` key in profile config

- packages/schema/src/user/index.types.ts
@keyshade/schema
Exports User type by inferring it from UserSchema  <br />
Fixes #573 
___
enhancement
___
- Added a new `User` type to the `@keyshade/schema` package by inferring it from the `UserSchema`.
- This change enhances the schema package by including the missing `User` entity definitions.
___
<tr>
<td>
<details>
<summary><strong>index.types.ts</strong><dd><code>Add User type inference from UserSchema</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/schema/src/user/index.types.ts
<li>Added import …
> feat(schema): Add User type inference from UserSchema

- packages/schema/src/secret/index.ts
- packages/schema/src/variable/index.ts
- packages/schema/tests/api-key.spec.ts
- packages/schema/tests/auth.spec.ts
- packages/schema/tests/enums.test.ts
- packages/schema/tests/environment.spec.ts
- packages/schema/tests/event.spec.ts
- packages/schema/tests/integration.spec.ts
- packages/schema/tests/pagination.spec.ts
- packages/schema/tests/secret.spec.ts
- packages/schema/tests/user.spec.ts
- packages/schema/tests/variable.spec.ts
- packages/schema/tests/workspace-membership.spec.ts
- packages/schema/tests/workspace-role.spec.ts
- packages/schema/tests/workspace.spec.ts
@keyshade/schema:
- Create describe blocks to contain tests for each kind of schema. Removed old test comments.
- Change count type from string to number in secret and variable RollbackResponses.
<br />
___
Tests
___
- Refactored all schema tests by introducing `describe` blocks for better organization and readability.
- Grouped existing test cases under appropriate `describe` blocks to enhance test structure.
- Added missing assertions and validation checks in some test files.
- Removed old test comments to clean up the test files.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><details><summary>13 files</summary><table>
<tr>
<td>
<details> …
> refactor(schema): add describe blocks in tests for each kind of schema

- apps/api/src/project/project.e2e.spec.ts
- apps/api/src/project/service/project.service.ts
- Created a condition for authorityCheck over environment when projects accesslevel is global. Previously the permittedAuthorites and authorites were compared, but a non member would not have those roles.
- Add environmentCount, variableCount, secretCount properties in a test.
Fixes #575
Previously:
Permitted Authorities for Workspace:
Authorities: READ_ENVIRONMENT,READ_SECRET,READ_VARIABLE
___
Bug fix, Tests
___
- Enabled and enhanced a test to verify that any user can access a global project, including checks for `environmentCount`, `secretCount`, and `variableCount`.
- Modified the authority check logic in the `ProjectService` to allow access to global projects without requiring specific authorities.
___
<table><thead><tr><th></th><th …
> fix(api): Enable global project access

- api-collection/Auth Controller/Logout.bru
- apps/api/src/auth/controller/auth.controller.ts
- apps/api/src/auth/service/auth.service.ts
Added a logout endpoint to the  auth.controller.ts file and the logout function in the auth.service.ts file. This endpoint clears the token cookie, ensuring the user is logged out securely.
Fixes #223 
NA
@rajdip-b 
___
Enhancement
___
- Added a new `logout` endpoint in the `auth.controller.ts` file to handle user logout by clearing the `token` cookie.
- Implemented a `logout` method in the `auth.service.ts` file that clears the `token` cookie and logs the action.
- Ensured the logout process sends a success message upon completion.
___ …
> feat(api): add logout endpoint to clear token cookie

- api-collection/Workspace Controller/Get all invitations of user.bru
- apps/api/src/environment/dto/create.environment/create.environment.ts
- apps/api/src/environment/environment.e2e.spec.ts
- apps/api/src/prisma/migrations/20241211205448_add_created_on_in_workspace_member/migration.sql
- apps/api/src/prisma/schema.prisma
- apps/api/src/workspace-membership/service/workspace-membership.service.ts
- apps/api/src/workspace-membership/workspace-membership.e2e.spec.ts
- apps/api/src/workspace/controller/workspace.controller.ts
- apps/api/src/workspace/service/workspace.service.ts
- apps/api/src/workspace/workspace.e2e.spec.ts
Created an endpoint /invitations under workspace to retrieve all unaccepted invitations. Three E2E Tests were also added.<br />
Fixes #550
Fixes #551
___
___
- Added a new API endpoint `/invitations` to fetch all workspace invitations for a user, with support for pagination and filtering by acceptance status.
- Implemented the `getInvitationsOfUser` method in the `WorkspaceService` to handle the logic for fetching and paginating invitations.
- Added end-to-end tests to verify the functionality of the new endpoint, including tests for filtering by accepted invitations.
___
<tr>
<td>
<details> …
> feat(api): Add endpoint to fetch all workspace invitations for a user

- apps/platform/src/app/layout.tsx
- apps/platform/src/components/common/online-status-handler.tsx
- apps/platform/src/hooks/use-online-status.ts
This PR introduces functionality to detect and display the online/offline status of the platform using a toast message.
Fixes #499 
N/A
N/A
@rajdip-b 
I have throttled the network for testing the functionality.
https://www.loom.com/share/10eb3fcf518b40179a4ce52f92b46fa7
___
enhancement
___
- Introduced `OnlineStatusHandler` component to manage online/offline status detection.
- Implemented `useOnlineStatus` hook to listen for network status changes and display toast notifications.
- Integrated the `OnlineStatusHandler` into the main application layout to provide real-time feedback on internet connectivity.
___
<tr> …
> feat(platofrm): Added online/offline status detection in the platform

- apps/api/src/environment/environment.e2e.spec.ts
- apps/api/src/mail/emails/components/base-email-template.tsx
- apps/api/src/mail/emails/workspace-invitation.tsx
- apps/api/src/mail/emails/workspace-removal.tsx
- apps/cli/src/commands/workspace.command.ts
- apps/cli/src/commands/workspace/membership.workspace.ts
- apps/cli/src/commands/workspace/membership/accept-invitation.membership.ts
- apps/cli/src/commands/workspace/membership/cancel-invitation.membership.ts
- apps/cli/src/commands/workspace/membership/decline-invitation.membership.ts
- apps/cli/src/commands/workspace/membership/get-all-members.membership.ts
- apps/cli/src/commands/workspace/membership/invite.membership.ts
- apps/cli/src/commands/workspace/membership/leave.membership.ts
- apps/cli/src/commands/workspace/membership/remove.membership.ts
- apps/cli/src/commands/workspace/membership/transfer-ownership.membership copy.ts
- apps/cli/src/commands/workspace/membership/update-role.membership.ts
- apps/cli/src/commands/workspace/role/update.role.ts
- apps/cli/src/util/controller-instance.ts
- package.json
Improves CLI functionality to now work with workspace membership. <br />
Fixes #548
___
Enhancement
___
Added new CLI functionality to manage workspace memberships:
- Created new workspace membership command structure with multiple subcommands
- Implemented commands for:
- Inviting/removing users from workspace
- Accepting/declining/canceling invitations
- Transferring workspace ownership
- Updating member roles
- Listing workspace members
- Added WorkspaceMembershipController integration
- Fixed formatting in email templates
___
<tr>
<td>
<details>
<summary><strong>membership.workspace.ts</strong><dd><code>Add …
> feat(cli): Add functionality to operate on Workspace Membership

- .github/workflows/validate-api-client.yaml
- .github/workflows/validate-api.yaml
- .github/workflows/validate-cli.yaml
- .github/workflows/validate-platform.yaml
- .github/workflows/validate-schema.yaml
- .github/workflows/validate-secret-scan.yaml
- .github/workflows/validate-web.yaml
- package.json
We encountered unexpected issues when internal dependencies in the apps were changed. Updating the existing workflows will help catch such errors early and prevent them in the future.<br />
The paths are currently optimized for amount of workflows running. Example: a change in schema will trigger api-client 
only and not workflows for platform and cli.
___
Enhancement
___
- Updated GitHub workflow configurations to include internal package dependencies in trigger paths
- Added schema package as dependency for api-client workflow
- Added api-client and secret-scan packages as dependencies for CLI workflow
- Added api-client package as dependency for platform workflow
- Changes ensure workflows run when dependent packages are modified, helping catch integration issues early
___ …
> feat(workflows): Add internal package dependencies to existing workflows

- .github/workflows/validate-api.yaml
- apps/api/src/auth/guard/api-key/api-key.guard.ts
- apps/api/src/prisma/migrations/20250109110640_add_admin_api_key_authority/migration.sql
- apps/api/src/prisma/schema.prisma
Added `ADMIN` authority for API keys. This allows an API key to be used as a master key. Having this authority linked to a key means that this API key can perform all the operations that can be performed by an API key.
___
Enhancement
___
- Added `ADMIN` authority to the `Authority` enum for API keys.
- Updated `ApiKeyGuard` to allow `ADMIN` authority to bypass checks.
- Created a migration script to add `ADMIN` authority to the database schema.
- Enhanced documentation in the schema for the `ADMIN` authority.
___
<tr>
<td>
<details>
<summary><strong>api-key.guard.ts</strong><dd><code>Update `ApiKeyGuard` to handle `ADMIN` authority</code>&nbsp; &nbsp; …
> feat(api): Add ADMIN authority for API keys

- packages/schema/src/workspace/index.ts
- packages/schema/src/workspace/index.types.ts
- packages/schema/tests/workspace.spec.ts
**Schema and relevant tests for Workspace's invitation lists**  <br />
Fixes #552
___
___
- Added schemas for `GetInvitationRequest` and `GetInvitationResponse`.
- Defined types for the new schemas in `index.types.ts`.
- Implemented validation tests for the new schemas.
- Enhanced workspace schema functionality with invitation-related features.
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Added schemas for workspace invitation handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/schema/src/workspace/index.ts
<li>Added …
> feat(schema): Add workspace invitation schema

- apps/cli/CHANGELOG.md
- apps/cli/package-lock.json
- apps/cli/package.json
- apps/cli/src/commands/secret/list.secret.ts
- apps/cli/src/commands/secret/revisions.secret.ts
- apps/cli/src/commands/secret/rollback.secret.ts
- apps/cli/src/commands/variable/revisions.variable.ts
- apps/cli/src/commands/variable/rollback.variable.ts
- apps/cli/src/commands/workspace/membership/cancel-invitation.membership.ts
- apps/cli/src/commands/workspace/membership/invite.membership.ts
- apps/cli/src/commands/workspace/membership/remove.membership.ts
- apps/cli/src/commands/workspace/membership/transfer-ownership.membership copy.ts
- apps/cli/src/commands/workspace/membership/update-role.membership.ts
- apps/cli/src/commands/workspace/role.workspace.ts
- apps/cli/src/commands/workspace/role/create.role.ts
- apps/cli/src/commands/workspace/role/update.role.ts
Enhancement, Documentation
___
- Refactored CLI commands to replace arguments with options.
- Updated command implementations to use descriptive option flags.
- Added new subcommands and improved workspace role management.
- Updated version to 2.1.0 and documented changes in the changelog.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>13 files</summary><table>
<tr>
<td><strong>list.secret.ts</strong><dd><code>Refactored secret list command to use options</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/keyshade-xyz/keyshade/pull/615/files#diff-2a60ffa339c54c754c130fc45b4cda2ef7dd8cc472e8e18c2c329f8f3031ae …
> refactor(cli): Replace arguments with options

- apps/platform/src/components/auth/auth-email-form.tsx
- apps/platform/src/components/auth/otp/otp-input-form.tsx
- apps/platform/src/lib/is-email-valid.ts
- apps/platform/src/lib/is-empty-string.ts
Fixed authentication page reload when authentication is submitted with an error.
Added new error message if email input field is empty
Fixes #993 
None
Empty email:
Incorrect email:
After error submission:
> refactor(auth): improve OTP and email validation in form

- bucket/keyshade.json
Automated scoop manifest update.
___
Other
___
- Update Keyshade CLI version from 2.34.0-stage.13 to 3.3.0-stage.2
- Fix download URL to point to correct release tag
- Move hash value to correct architecture section
- Remove redundant bin hash configuration
___
```mermaid
flowchart LR
A["Version 2.34.0-stage.13"] --> B["Version 3.3.0-stage.2"]
C["Incorrect URL"] --> D["Fixed Release URL"]
E["Misplaced Hash"] --> F["Corrected Hash Location"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>keyshade.json</strong><dd><code>Update Scoop manifest for new CLI version</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> chore(scoop): update to 2.34.0-stage.13
