keyshade-xyz/keyshade

package.json

enhancement
___
This PR includes an update to the license in the package.json file:
- The license has been changed from MIT to MPL-2.0.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td>
<details> …

update license to MPL-2.0

---

.github/workflows/api.yaml
.github/workflows/cli.yaml
.github/workflows/sdk-node.yaml
.github/workflows/web.yaml

enhancement
___
This PR introduces two new GitHub Actions workflows for the CLI and SDK-Node packages. The workflows are triggered on push and pull request events that affect the respective package paths. Each workflow includes steps for:
- Checking out the code
- Setting up Node.js
- Installing pnpm
- Installing packages
- Running lint
- Running tests
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

build: Add Lint Workflows for `cli` and `sdk-node`

---

.github/workflows/auto-assign.yaml
CONTRIBUTIONS.md

Enhancement
___
This PR introduces a new GitHub Actions workflow that automates the assignment of issues. The key changes include:
- A new workflow file `.github/workflows/auto-assign.yaml` has been added.
- The workflow triggers on the creation of an issue comment.
- If a user comments "/attempt" on an unassigned issue, the issue gets assigned to them.
- If the issue is already assigned, a comment is added to inform the user.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

feat: added the auto assign workflow yaml file

---

.github/workflows/auto-assign.yaml

bug_fix
___
This PR addresses a bug in the auto-assign feature of the GitHub workflows. The main changes include:
- Fixing the issue where the auto-assign feature was failing due to trying to read properties of undefined assignees.
- Using the correct methods to add assignees and create comments on issues.
- Explicitly defining and using the owner and repo variables in the API calls.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix: issue auto assign cannot read properties of undefined assignees

---

package.json

Updated the `prepare` script in `package.json` to use the new `husky` command instead of the deprecated `husky install`. <br />
Fixes #201
None
None
None
None
---
enhancement
---
- Updated the `prepare` script in `package.json` to use the new `husky` command instead of the deprecated `husky install`.
---
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update Husky Command in package.json</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Updated the …

chore: Update deprecated husky Install command

---

apps/api/jest.e2e-config.ts
apps/api/src/app/app.module.ts
apps/api/src/common/alphanumeric-reason-pipe.spec.ts
apps/api/src/common/alphanumeric-reason-pipe.ts
apps/api/src/common/authority-checker.service.ts
apps/api/src/common/cleanup.ts
apps/api/src/common/create-event.ts
apps/api/src/common/get-collective-project-authorities.ts
apps/api/src/integration/controller/integration.controller.spec.ts
apps/api/src/integration/controller/integration.controller.ts
apps/api/src/integration/dto/create.integration/create.integration.spec.ts
apps/api/src/integration/dto/create.integration/create.integration.ts
apps/api/src/integration/dto/update.integration/update.integration.spec.ts
apps/api/src/integration/dto/update.integration/update.integration.ts
apps/api/src/integration/integration.e2e.spec.ts
apps/api/src/integration/integration.module.ts
apps/api/src/integration/integration.types.ts
apps/api/src/integration/plugins/base.integration.ts
apps/api/src/integration/plugins/discord/discord.integration.spec.ts
apps/api/src/integration/plugins/discord/discord.integration.ts
apps/api/src/integration/plugins/factory/integration.factory.spec.ts
apps/api/src/integration/plugins/factory/integration.factory.ts
apps/api/src/integration/service/integration.service.spec.ts
apps/api/src/integration/service/integration.service.ts
apps/api/src/prisma/migrations/20240501060445_add_integration/migration.sql
apps/api/src/prisma/schema.prisma
apps/api/src/variable/controller/variable.controller.ts
apps/api/src/workspace/controller/workspace.controller.ts
pnpm-lock.yaml

- Added base support for creating and managing integrations
- Added plug-and-play infra, allowing community to create integrations easily
- Added discord plugin
Fixes #123 
Fixes #125

feat(api): Add Integration support

---

apps/api/jest.e2e-config.ts
apps/api/src/api-key/api-key.e2e.spec.ts
apps/api/src/api-key/controller/api-key.controller.ts
apps/api/src/api-key/service/api-key.service.ts
pnpm-lock.yaml

___
- Integrated `ApiKeyService` into API key end-to-end tests, enhancing test modularity and maintainability.
- Implemented `beforeEach` and `afterEach` hooks for setting up and tearing down test data, improving test isolation.
- Updated test assertions to be more concise and focused on essential attributes.
- Adjusted Jest configuration to specifically run API key tests, ensuring targeted test execution.
___
<tr>
<td>
<details>
<summary><strong>api-key.e2e.spec.ts</strong><dd><code>Refactor API Key E2E Tests with Service Integration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

test(api): Refactored e2e tests

---

apps/platform/src/lib/api-client.ts

Fixes #[ISSUENO]
___
enhancement
___
- Added a `delete` method to the `APIClient` class in `api-client.ts` to support DELETE HTTP requests.
- The new method enhances the API client by allowing deletion operations, configured to handle credentials and JSON content types.
___
<tr>
<td>
<details>
<summary><strong>api-client.ts</strong><dd><code>Add DELETE Method to APIClient …

feat(platfrom): add delete method in api client

---

apps/web/Dockerfile

Fixes #[ISSUENO]
___
bug_fix
___
- Corrected the Dockerfile to copy the correct `next.config.mjs` instead of `next.config.js`, resolving the build failure issue.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix
<tr>
<td>
<details>
<summary><strong>Dockerfile</strong><dd><code>Fix Docker Build by Correcting Config File Extension</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
apps/web/Dockerfile
<li>Changed the …

fix(web): Docker next config not found

---

apps/api/src/workspace/service/workspace.service.ts
apps/api/src/workspace/workspace.e2e.spec.ts

Tests, Enhancement
___
- Added a check in `WorkspaceService` to prevent assigning the admin role to users.
- Introduced a new method `getWorkspaceAdminRole` to fetch admin role details.
- Updated `addMembersToWorkspace` method to include admin role check.
- Refactored e2e tests to use `userService.createUser` for user creation.
- Added new tests to ensure admin role cannot be assigned to users.
- Updated existing tests to align with the new role assignment logic.
- Added comments in tests for better understanding of the steps involved.
___
<tr>
<td>
<details>
<summary><strong>workspace.service.ts</strong><dd><code>Prevent assigning admin role to users …

test: Refactored workspace e2e tests

---

docker-compose.yml
pnpm-lock.yaml

Added `700` permission to the directory created by the postgres db in docker compose. <br />
A
Fixes #245 
@rajdip-b 

fix(docker): Grant correct permissions to docker image

---

docs/contributing-to-keyshade/environment-variables.md

Docs: added REDIS_URL and REDIS_PASSWORD to environment-variable.md <br />
Fixes #183
- [X ] I have made the necessary updates to the documentation.

docs: modified environment-variable.md

---

docs/contributing-to-keyshade/running-things-locally/running-the-web-app.md
docs/contributing-to-keyshade/running-things-locally/running-the-web-package.md

Added running-the-web-app.md to the running-things-locally folder in the docs <br />
Fixes #[185]
- [X ] I have made the necessary updates to the documentation, or no documentation changes are required.
___
Documentation
___
- Added a new markdown file `running-the-web-app.md` with detailed instructions on how to run the web app locally.
- Included commands for:
- Running the Next.js development environment.
- Running tests using Jest.
- Provided a URL for viewing the web app.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation
<tr>
<td>
<details>
<summary><strong>running-the-web-package.md</strong><dd><code>Added documentation for running the web package locally.</code>&nbsp; </dd></summary>
<hr> …

docs: added running-the-web-app.md

---

docs/contributing-to-keyshade/running-things-locally/running-the-api.md
docs/contributing-to-keyshade/setting-things-up.md

Documentation
___
- Removed Docker Compose instructions from `running-the-api.md`.
- Added detailed Docker Compose setup instructions in `setting-things-up.md`, including:
- Steps to start dependencies (PostgreSQL, Redis, Minio) using Docker Compose.
- Required ports for the services.
- Troubleshooting tips for PostgreSQL.
- Instructions for shutting down the Docker infrastructure.
___
<tr>
<td>
<details>
<summary><strong>running-the-api.md</strong><dd><code>Remove Docker Compose instructions for API setup</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

docs: Added docker details in setting-things-up.md

---

apps/platform/src/app/auth/otp/page.tsx
apps/platform/src/components/ui/input-otp.tsx
package.json

Added sonner rich text warning message for invalid otp
Fixes #332 
[shadcn/ui-Sonner](https://ui.shadcn.com/docs/components/sonner)
___
Enhancement, Bug fix
___
- Added a warning toast message using `sonner` for invalid OTP input.
- Prevented default form submission behavior on OTP verification button click.
- Simplified the `setOtp` function call in the OTP input component.
- Added type definition for `OTPInputProps` in the `InputOTP` component.
___
<tr>
<td>
<details> …

feat(platform): Add warning sonner toast for invalid otp

---

.github/workflows/validate-platform.yaml
apps/api/src/user/service/user.service.ts

- Adding validate platform workflow. 
Fixes #318
N/A
N/A
@rajdip-b 
N/A

chore(ci): Adding validate pipeline

---

.github/workflows/validate-cli.yaml
package.json

adding validate cli pipeline
Fixes #317
N/A
N/A
@rajdip-b 
N/A

chore(ci): Add validate CLI pipeline

---

apps/api/src/common/paginate.spec.ts
apps/api/src/common/paginate.ts

- Improve paginate module to handle cases when page is greater or equal to maximum page limit and when limit is 0. Paginate method will return empty object on such cases.
- Add unit tests for such cases.
___
___
- Updated the `paginate` function to handle cases where the page exceeds the maximum page limit and when the limit is 0 or undefined, returning an empty object in such cases.
- Added and modified unit tests to cover these edge cases.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>paginate.spec.ts</strong><dd><code>Add and modify test cases for paginate function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

feat(api): Improve handling of edge cases for paginate module

---

.github/workflows/docker-ci.yml
apps/platform/Dockerfile
apps/web/Dockerfile

CI which checks docker build whenever changes are done in docker file 
Fixes #131
N/A
N/A
@rajdip-b 

chore(ci): Add docker check  

---

apps/api/src/workspace/service/workspace.service.ts

Added validation to ensure that If a workspace role is provided in the `roleIds` array doesn't exist, a `NotFoundException` is thrown.
Fixes #405 
No new dependencies were added.

fix(api): Add NotFound exception on passing an invalid roleId while inviting user in workspace

---

packages/api-client/jest.config.ts
packages/api-client/src/controllers/environment.ts
packages/api-client/src/controllers/integration.ts
packages/api-client/src/controllers/project.ts
packages/api-client/src/controllers/secret.ts
packages/api-client/src/controllers/variable.ts
packages/api-client/src/controllers/workspace-role.ts
packages/api-client/src/controllers/workspace.ts
packages/api-client/src/core/pagination-parser.ts
packages/api-client/src/types/environment.types.d.ts
packages/api-client/src/types/event.types.d.ts
packages/api-client/src/types/index.types.d.ts
packages/api-client/src/types/integration.types.d.ts
packages/api-client/src/types/project.types.d.ts
packages/api-client/src/types/secret.types.d.ts
packages/api-client/src/types/variable.types.d.ts
packages/api-client/src/types/workspace-role.types.d.ts
packages/api-client/src/types/workspace.types.d.ts
packages/api-client/tests/workspace-role.spec.ts

Fixes #355
___
___
- Implemented a new `WorkspaceRoleController` to manage workspace roles, including methods for creating, updating, deleting, and fetching roles.
- Defined TypeScript types for workspace role operations, ensuring type safety and clarity in API interactions.
- Added comprehensive tests for the `WorkspaceRoleController`, covering all CRUD operations and role existence checks.
- Updated Jest configuration to focus on workspace role tests, ensuring targeted and efficient test execution.
___
<tr>
<td>
<details>
<summary><strong>workspace-role.ts</strong><dd><code>Implement Workspace Role Controller with CRUD …

feat(api-client): Added workspace role controller

---

apps/api/src/project/project.e2e.spec.ts
apps/api/src/project/service/project.service.ts

Sending total Count of env,variable and secrets when fetching project data for a workspace
Fixes #308 
- [] Need to update postman
Sample response
```{
"items": [
{
"id": "c6d92085-0e85-4986-a1d3-7923583efa22",
"name": "Project 1",
"slug": "project-1-oa2j9",
"description": "Dummy project 1",
"createdAt": "2024-09-13T15:45:42.014Z",
"updatedAt": "2024-09-13T15:45:42.014Z",
"storePrivateKey": true,
"isDisabled": false,
"accessLevel": "PRIVATE",
"isForked": false,
"lastUpdatedById": "cm0v65bm00000130sigtvry7y",
"workspaceId": "3b41add3-4e14-4866-a6e8-0669d1d7b08b",
"forkedFromId": null,
"totalEnvironmentsOfProject": 3,
"totalVariablesOfProject": 1,
"totalSecretsOfProject": 1
},
{
"id": "45dae533-8556-4621-b841-43502fe85752",
"name": "Project 2",
"slug": "project-2-o9rl4",
"description": …
```

feat(api): Fetch total count of environments, secrets and variables in project

---

docs/cli/project.md

This PR adds documentation for the new project feature in the CLI, providing users with clear instructions on how to utilize this functionality effectively.
Fixes #456 
Consider adding examples for common use cases of the scan feature in future documentation updates.
@rajdip-b 
N/A
___
Documentation
___
- Added detailed documentation for the `project` command in the CLI, covering all subcommands and their usage.
- Provided examples and descriptions for each subcommand, including `create`, `delete`, `fork`, `get`, `list-forks`, `list`, `sync`, `unlink`, and `update`.
- Included information on options and arguments for each subcommand to guide users effectively.
___ …

docs: Add documentation for project in CLI

---

apps/api/src/common/env/env.schema.ts
apps/api/src/main.ts

Added input range validation for Sentry env vars
Fixes #145 
No new deps introduced.
None at the moment.
@rajdip-b 
N/A
___
___
- Added URL validation for `SENTRY_DSN` and range validation for `SENTRY_TRACES_SAMPLE_RATE` and `SENTRY_PROFILES_SAMPLE_RATE` in environment schema.
- Enhanced Sentry initialization with detailed logging of configuration parameters.
- Implemented error handling during Sentry initialization to capture exceptions.
- Changed import for `ProfilingIntegration` to `nodeProfilingIntegration`.
___
<tr>
<td>
<details> …

feat: Add more logging to Sentry init

---

apps/cli/src/commands/secret/list.secret.ts

Removed an unnecessary console log <br />
Fixes #302 
___
enhancement
___
- Removed an unnecessary console log statement from the `ListSecret` command in the CLI application.
- This change enhances the code by cleaning up redundant output, improving readability and performance.
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<tr>
<td>
<details>
<summary><strong>list.secret.ts</strong><dd><code>Remove unnecessary console log from ListSecret command</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
apps/cli/src/commands/secret/list.secret.ts
<li>Removed an unnecessary console log statement.<br> <li> Improved code readability …

fix(cli): Removed unnecessary console log in secrets

---

package.json
turbo.json

updated the turbo package and made the required changes in turbo.json <br />
Fixes #542 
@rajdip-b
___
enhancement, configuration changes
___
- Updated the `turbo` package in `package.json` to version `^2.3.1`.
- Modified `turbo.json` configuration to replace `pipeline` with `tasks` and adjusted task inputs for compatibility with the new version.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update turbo package to latest version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
- Updated `turbo` package …

chore: Update Turbo to 2.3.1

---

apps/platform/src/components/dashboard/variable/addVariableDialogue/index.tsx
apps/platform/src/components/dashboard/variable/confirmDeleteVariable/index.tsx
apps/platform/src/components/dashboard/variable/variableList/index.tsx

- Fixed an error where the variable list would not update after a variable was added
- Fixed an error where an infinite loading message would should after a variable was deleted<br />
Fixes #1096 
N/A
N/A
Teammates:
@maethlucky 
@m1r9n1 
https://github.com/user-attachments/assets/752f1f17-024f-4bee-b879-1e2f29c464c2
___
Bug fix
___
- Fixed variable list not refreshing after adding new variable
- Fixed infinite loading state when deleting variables
- Improved state management for dialog close operations
___
```mermaid
flowchart LR
A["Add Variable Dialog"] -- "triggers refresh" --> C["Variable List"]
B["Delete Variable Dialog"] -- "triggers refresh" --> C
C -- "refetches data" --> D["Updated Variable Display"]
```
<details> <summary><h3> File …

fix(platform): update variable list after add or delete issue

---

apps/platform/src/components/dashboard/secret/secretCard/index.tsx
apps/platform/src/components/dashboard/variable/variableCard/index.tsx

- Fixed bugged corner UI on the secret and variable pages on the app <br />
Fixes #1079 
N/A
N/A
Teammates:
@maethlucky 
@m1r9n1 
___
Bug fix
___
- Fixed corner radius positioning in table headers
- Removed incorrect `rounded-tr-xl` from Version column
- Applied proper corner radius to last table column
___
```mermaid
flowchart LR
A["Table Header"] --> B["Environment Column"]
B --> C["Value Column"] 
C --> D["Version Column"]
D --> E["Actions Column"]
D -- "remove rounded-tr-xl" --> D2["Version Column Fixed"]
E -- "keep rounded-tr-xl" --> E2["Actions Column (Last)"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug …

fix(platform): corner radius in wrong place for secret and variable

---

apps/api/src/auth/auth.controller.ts
apps/api/src/auth/service/auth.service.ts
apps/api/src/mail/emails/components/share-base-email-template.tsx
apps/api/src/mail/emails/login-notification-email.tsx
apps/api/src/mail/emails/share-secrete-email.tsx
apps/api/src/mail/emails/styles/common-styles.ts
apps/api/src/mail/emails/workspace-invitation.tsx
apps/api/src/mail/services/interface.service.ts
apps/api/src/mail/services/mail.service.ts

Fixes #1101
___
Enhancement
___
- Redesigned email templates with new branding and layout
- Enhanced login notification email with detailed device information
- Added date and time tracking to authentication flows
- Updated email styling with new color scheme and components
___
```mermaid
flowchart LR
A["Auth Service"] --> B["Parse Login Request"]
B --> C["Extract Date/Time"]
C --> D["Send Login Notification"]
D --> E["Enhanced Email Template"]
E --> F["New Branding & Layout"]
F --> G["Social Media Footer"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>10 files</summary><table>
<tr> …

feat: Update email design

---

apps/platform/src/components/shared/sidebar/index.tsx

This PR addresses a minor UI inconsistency where the left padding was slightly larger than intended. The padding is now adjusted to match the right side, ensuring consistent spacing and a more balanced layout.
Fixes #1123 
N/A
N/A
@rajdip-b 
___
Bug fix
___
- Adjust sidebar margin to fix UI inconsistency
- Replace uniform margin with specific left/right margins
- Ensure balanced layout spacing
___
```mermaid
flowchart LR
A["Sidebar Component"] -- "Change margin" --> B["Balanced Layout"]
A -- "m-8 → ml-4 mr-8" --> B
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details> …

fix(platform): adjust margin for sidebar component

---

apps/platform/src/app/(main)/(settings)/[workspace]/settings/page.tsx

This PR ensures both the workspace name and its icon are perfectly center aligned, improving visual consistency and overall UX.
Fixes #1119 
N/A
N/A
@rajdip-b 
___
Bug fix
___
- Remove unnecessary empty div from workspace settings layout
- Fix center alignment of workspace name and icon
___
```mermaid
flowchart LR
A["Workspace Settings Layout"] --> B["Remove Empty Div"]
B --> C["Improved Alignment"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>page.tsx</strong><dd><code>Remove empty div from workspace header</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix: center align workspace name and icon

---

apps/web/src/components/shared/navbar/index.tsx

Fixes #[ISSUENO]
___
Enhancement
___
- Added "Book a Demo" navigation link to navbar
- Links to external Cal.com scheduling page
___
```mermaid
flowchart LR
navbar["Navbar Component"] -- "adds link" --> demo["Book a Demo"]
demo -- "redirects to" --> cal["cal.com/keyshade/demo"]
```
<tr>
<td>
<details> …

feat: add book a demo

---

apps/platform/src/components/dashboard/project/projectCard/index.tsx

Fixes an issue where project avatars and icons in the bottom right would shrink in size because of resizing and long project names. Prevents this behavior from occurring by truncating project names and adjust certain HTML/CSS properties
Fixes #1138
None
None
None
Before Changes:
After Changes:
___
Bug fix
___
- Fix project icon shrinking issue on dashboard
- Prevent avatar resizing with long project names
- Add text truncation for project names and descriptions
- Improve layout with proper flex properties
___
```mermaid
flowchart LR
A["Project Card Layout"] --> B["Add flex-shrink-0 to avatar"]
A --> C["Add min-width-0 to containers"]
A --> D["Add text truncation"]
B --> E["Fixed Icon Size"]
C --> F["Proper Text Overflow"]
D --> F
```
<details> …

fix(platform): project icon alignment issue on dashboard

---

bucket/keyshade.json

Automated scoop manifest update.
___
Other
___
- Update Scoop manifest version to `2.34.0-stage.13`
- Add hash field to bin configuration
___
```mermaid
flowchart LR
A["Scoop Manifest"] --> B["Version Update"]
A --> C["Hash Addition"]
B --> D["2.34.0-stage.13"]
C --> E["SHA256 Hash"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>keyshade.json</strong><dd><code>Update Scoop manifest version and hash</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
bucket/keyshade.json
<ul><li>Update …

chore(scoop): update to 2.34.0-stage.13

---

apps/cli/CHANGELOG.md
apps/cli/package.json
apps/cli/src/commands/init.command.ts
package.json
pnpm-lock.yaml

where private key is not there- (and for if it's there just ignore the private key step)
___
Enhancement
___
- Enhanced CLI init command with interactive workspace/project/environment selection
- Added API integration to fetch and display available options
- Improved user experience with dropdown menus instead of manual input
- Added automatic private key retrieval from project data
___
```mermaid
flowchart LR
A["User runs init command"] --> B["Fetch workspaces from API"]
B --> C["Select workspace from dropdown"]
C --> D["Fetch projects for workspace"]
D --> E["Select project from dropdown"]
E --> F["Auto-retrieve private key"]
F --> G["Fetch environments for project"]
G --> H["Select environment from dropdown"]
H --> I["Write configuration files"]
```
<details> <summary><h3> File …

feat(cli): make init command dynamically fetch config

---

apps/platform/src/components/integrations/integrationList/index.tsx

Used getAllRunsOfIntegration to display the number of actions that have occurred for a given integration instead of the number of different triggers <br />
Fixes #1126 
N/A
N/A
Thank you @rajdip-b and @Souvik9205 for your help!
https://github.com/user-attachments/assets/b57744f3-4a69-4e47-9084-d4320295b68a
___
Bug fix
___
- Fixed trigger count display to show actual runs instead of configured triggers
- Added API call to fetch integration run counts
- Implemented state management for run counts per integration
___
```mermaid
flowchart LR
A["Integration List"] --> B["Fetch All Integrations"]
B --> C["For Each Integration"]
C --> D["Get Integration Runs"]
D --> E["Update Run Counts State"]
E --> F["Display Actual Run Count"]
```
<details> <summary><h3> …

fix(platform): trigger count now displays correct number of triggers
